;;; ready-player-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ready-player.el

(defvar ready-player-mode nil "\
Non-nil if Ready-Player mode is enabled.
See the `ready-player-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `ready-player-mode'.")
(custom-autoload 'ready-player-mode "ready-player" nil)
(autoload 'ready-player-mode "ready-player" "\
Toggle Ready Player mode media file recognition.

See `ready-player-supported-media' for recognized types.

This is a global minor mode.  If called interactively, toggle the
`Ready-Player mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='ready-player-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'ready-player-add-to-auto-mode-alist "ready-player" "\
Add media recognized by `ready-player-mode'.")
(register-definition-prefixes "ready-player" '("ready-player-"))

;;; End of scraped data

(provide 'ready-player-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ready-player-autoloads.el ends here
