;;; imgbb-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from imgbb.el

(autoload 'imgbb-upload "imgbb" "\
Upload FILENAME to imgbb.com, show the image url and put it into the kill ring.

(fn FILENAME)" t)
(register-definition-prefixes "imgbb" '("imgbb-"))

;;; End of scraped data

(provide 'imgbb-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; imgbb-autoloads.el ends here
