;;; terminal-toggle-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from terminal-toggle.el

(autoload 'terminal-toggle "terminal-toggle" "\
Show/launch or hide terminal." t)
(register-definition-prefixes "terminal-toggle" '("terminal-toggle-"))

;;; End of scraped data

(provide 'terminal-toggle-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; terminal-toggle-autoloads.el ends here
