;;; move-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from move-mode.el

(autoload 'move-mode "move-mode" "\
Major mode for Move source code.

\\{move-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.move\\'" . move-mode))
(register-definition-prefixes "move-mode" '("move-"))

;;; End of scraped data

(provide 'move-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; move-mode-autoloads.el ends here
