[manager] 
ratio = [ 2, 2, 4] 
sort_by = "alphabetical" 
sort_sensitive = false 
sort_reverse = false 
sort_dir_first = true 
linemode = "none" 
show_hidden = true 
show_symlink = true 
scrolloff = 5

[show_hidden]
show_hidden = true

[preview] 
tab_size = 4 
max_width = 1200
max_height = 500 
cache_dir = "" 
image_filter = "triangle" 
image_quality = 89 
sixel_fraction = 15 
ueberzug_scale = 3 
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]

edit = [
    { run = 'emacs -nw "$1"', desc = "$EDITOR", block =true, for = "unix"}
]

open_pptx = [
    { run = 'xournal "$1"', desc = "Open PowerPoint", for = "windows" ,
	{ run = 'xournal "$1"', desc = "Open PowerPoint", for = "linux" },
]
open_nomacs = [
    { run = 'nomacs "$1"', desc = "Open with Nomacs", for = "linux" },
]

open_zathura = [
    { run = 'zathura "$1"', desc = "Open with Zathura", for = "linux" },
]
open = [
    { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
]

extract = [
    { run = 'unar "$1"', desc = "Extract here", for = "unix" },
]

play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
    { mime = "application/pdf", use = ["open_zathura", "reveal"] },
    { mime = "image/*", use = ["open_nomacs", "reveal"] },  # Updated to use Nomacs
    { mime = "text/*", use = ["open_text_editor"] },
    { mime = "application/vnd.openxmlformats-officedocument.presentationml.presentation", use = ["open_pptx", "reveal"] }, 
    { name = "*/", use = ["edit", "open", "reveal"] },
    { mime = "{audio,video}/*", use = ["play", "reveal"] },
    { mime = "*", use = ["open", "reveal"] },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]
suppress_preload = false

[plugin]
preloaders = [
    { name = "*", cond = "!mime", run = "mime", multi = true, prio = "high" },
    { mime = "image/*", run = "image" },
    { mime = "video/*", run = "video" },
    { mime = "application/pdf", run = "pdf" },
]

previewers = [
    { mime = "image/*", run = "image" },
    { mime = "video/*", run = "video" },
    { mime = "application/pdf", run = "pdf" },
]

[input]
cd_title  = "Change directory:"
cd_origin = "top-center"
cd_offset = [ 0, 2, 50, 3 ]

[log]
enabled = true  
