# config - this links dotfiles to /usr/local/bin
# terminal config
ln -s ~/.dotfiles/sh/convert/convert_webloc_jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/webloc_jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/file/filecopyimgmultiple_1.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/move/FI_^.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/cnv_jpg_pdf.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/convert_heic_to_jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/convert_heic_to_jpg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/convert_png_j.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/convert_webloc_to_jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/convert_webp_jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/delete/clean.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/delete/X.fish
ln -s ~/.dotfiles/sh/delete/X.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/export/F2_txt.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/maketiny/compress_video.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/maketiny/compress_video2.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/plan/0T5.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/rename/F2_date_taken.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/heic_jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/jfif_jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/delete/deldoop.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/delete/deldoop2.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/delete/delete_all_heic.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/delete/delete_all_jfif.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/delete/delete_duplicate_images.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/delete/delete_duplicates.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/delete/delete_text_string.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/file/copy_clip2.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/file/filecopyimg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/file/filecopyimgmultiple.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/file/filecopyimgmultiple02.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/file/filecopyimgmultiple03.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/file/filepath.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/file/filepathcopy.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/launch/ghostty-launcher.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/make/mkdup.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/crop.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/rename/f2.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/rename/iph.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/mp4_frames.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/psd_convert.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/launch/open_tvpaint (2).sh /usr/local/bin/
ln -s ~/.dotfiles/sh/launch/open_tvpaint.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/launch/syncthing.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/make/mkpdf.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/make/screen_record
ln -s ~/.dotfiles/sh/psd/psd_bright_pencil.py
ln -s ~/.dotfiles/sh/psd/psd_bw.py
ln -s ~/.dotfiles/sh/psd/psd_fill.py
ln -s ~/.dotfiles/sh/psd/psd_fill.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/psd_fill_extra.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/psd_fill_working.py
ln -s ~/.dotfiles/sh/psd/psd_flat.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/psd_flats.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/psd_jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/psd_jpeg_w_gimp.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/psd_key_matte_folder.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/psd_key_matte_folder_strong.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/psd_keyout.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/psd_keyout_soft.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/psd_keyout_w_matte.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/psd_keyout_w_matte_soft.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/psd_select_sub.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/rename/rename.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/rename/rename_blank.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/rename/rename_date_taken.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/rename/rename_folder.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/rename/rename_still_life.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/rename/rm_not_cropped.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/untar.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/webloc_jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/make/yt-dl.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/F2.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/F2_date_taken_1.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/F2_folder.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/F2iph.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/F2iph.sh /usr/local/bin/~
ln -s ~/.dotfiles/sh/shell_files/filecopyimg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/filecopyimgmultiple.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/filecopyimgmultiple02.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/filecopyimgmultiple03.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/filepath.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/filepathcopy.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/forward_slashes-to-backward_slashes.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/ghostty-launcher.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/heic__jpg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/heic_jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/jfif_jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/move_files_to_parent.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/png-j.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/png-recursive.ps1
ln -s ~/.dotfiles/sh/shell_files/psd2jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/psd_convert.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/psd_jpeg_w_gimp.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/syncthing.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/tiny_vid.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/UTO.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/webloc_jpeg_02.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/webloc_jpeg_1.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/webp_jpeg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/X.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/X_all_heic.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/X_all_jfif.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/X_duplicate_images.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/X_duplicates.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/X_text_string.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/Xdoop.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/Xdoop_1.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/format/to_latex.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/cnv_pdf_jpg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/convert/cnv_pdf__jpg.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/format/grep_thumbnails.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/format/grep_thumbnails.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/format/grep_t.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/file/FI_^^.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/export/copy_out.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/export/export_org_to_pdf_02.org
ln -s ~/.dotfiles/sh/export/export_org_to_pdf_02.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/format/bracket_format.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/16x9.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/psd/16x92.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/make/mkto.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/make/autocaption.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/maketiny/tiny_vid_split.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/make/merge_mp3.bash
ln -s ~/.dotfiles/sh/export/export_org_to_pdf.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/make/autocaption_1.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/launch/syncthing_stop.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/make/save_screen.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/shell_files/F2_date_taken.sh /usr/local/bin/
ln -s ~/.dotfiles/sh/export/sequence_.sh /usr/local/bin/
