#target photoshop
app.bringToFront();
var files = [];
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\20250125\\1 Lineart AUTO MATTE.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\20250125\\Canvas's.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\20250125\\layer naming.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\20250125\\Save.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\20250125\\Set 1.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\20250125\\The Canvas.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\20250125\\The Color.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\20250125\\The Line.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\1 Lineart AUTO MATTE.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\10 GRADIENT SHADE MULTIPLY.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\11 GRADIENT LIGHT 50_ SCREEN.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\12 - PRESET SHADE n LIGHT.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\12_30 .atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\13 - ALPHATONE.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\1-Canvas's.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\2 Matte Fill Value and Tint.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\3 SHADE MULTIPLY.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\3. Animation Set V2.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\4 RIM LIGHTS (HARD).atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\5 RIM LIGHTS (SOFT)(Shallow).atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\6 BASIC RADIAL SHADOW + LIGHT.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\7 LIGHT SCREEN.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\8 SATIN SHADE 50_ MULTIPLY.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\9 SATIN LIGHT 50_ SCREEN.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\Actions.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\ADD LINE ART TO FILL (Seperate Layer).atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\ADD LINEART TO FILL (same layer).atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\Animation Set.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\Animation Shortcuts.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\Canvases .atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\cutting_edge_storyboards.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\Guides.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\layer naming.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\Layers.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\levels.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\POST1-COMIC HALFTONE PASS.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\POST2-ARTISTIC EXPERIMENT.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\Post3- ComputerFX.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\Save.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\The Canvas.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\The Color.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\The Line.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\Zack Actions V2 .atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\Zack Actions V3 .atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\actions\\Zack Actions V4 .atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\SergioPhotoshopActions\\SergioActions4.atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\SergioPhotoshopActions\\SergioSwatches.aco");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Actions\\Start Oct_06 .atn");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Bobby_Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Dan Luv Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Dan LuVisi - Brush Pack 1.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\danzedig.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\darekzabrock.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\DaveRapozaBrushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Florian Aupetit - Brush Pack 1.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Greg_Lindsay_Art_set_1.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Jaime_s Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Jashins_Brushes_5.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Kaye_brush.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Kyle Webster\\Kyle Builder Brush.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Kyle Webster\\Kyle Color Jumpers.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Lu Dongjun Brushes\\Lu Dongjun Brush fish brush .abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Lu Dongjun Brushes\\Lu Dongjun Brush Lesson01_Jungle_Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Lu Dongjun Brushes\\Lu Dongjun Brush Lesson02_Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\MaCa_BRUSHIO_00.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Makkon_sketchingBrushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Mark Molnar 2013 .abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\masaaki 2.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\MonicaWeasley_TreeExtensions_v2.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Nelbert_Brush_Set.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Nurzhan Bekkaliyev brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\PS-AMARO & WALDEN BRUSH.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\RamonN90_Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\sanami276_oldpaper.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\sandara_small_set.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\sergey Sketch Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\shiyoon_inkbrush.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Sparth - Extended Nature pack.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\thomasscholes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\Tonko House - Dice Tsutsumi and Robert Kondo - Brush Pack 1.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\ULTIMATE_STEVEAHN!.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\zedig .abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\zedig vol 2.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Artist_Packs\\zedig vol 3.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Collected_Collections\\Collected_From_Other_Packs\\actions\\Brushes November 22 .abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Collected_Collections\\Collected_From_Other_Packs\\SergioPhotoshopActions\\SergioBrushes01.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Comics_Halftone\\9 screentone BRUSHES by Violane Briat .abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Comics_Halftone\\crosshatch.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Comics_Halftone\\halftones_and_screentones.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Comics_Halftone\\manga.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Comics_Halftone\\rakes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Concept_Animation\\class.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Concept_Animation\\concept.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Concept_Animation\\dreamworks brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Concept_Animation\\el tigre brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Concept_Animation\\Eye_StudySet2.0.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Concept_Animation\\EyeBrushes like it_s literally just eyes .abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Concept_Animation\\Hair Brushes and Bush Brushes .abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Concept_Animation\\Meta Brushes l.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Concept_Animation\\nice for working in animation .abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Concept_Animation\\NinjaBrushes04.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Dry_Media\\art_markers.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Dry_Media\\dry_media.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Dry_Media\\Pencil Set_Vol02.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Dry_Media\\Sketch Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Favorites\\Favs.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\General_Collections\\Brushes 2022.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\General_Collections\\brushes for me.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\General_Collections\\brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\General_Collections\\brushes_june_2014.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\General_Collections\\brushes2.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\General_Collections\\brushes7.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\General_Collections\\BrushesJul2014.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\General_Collections\\megapack.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\General_Collections\\more brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\General_Collections\\new february brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\General_Collections\\U2644 Brushes 2011 (1).abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\General_Collections\\Untitled Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Ink_Linework\\1 Thin Block Boy.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Ink_Linework\\copier.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Ink_Linework\\EyecagerLine.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Ink_Linework\\fa_calligraphy_brushes_2.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Ink_Linework\\letterers.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Ink_Linework\\lineweightbrush.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Ink_Linework\\runny_inkers.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Ink_Linework\\swang_brushes_cc_gumroad.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Ink_Linework\\tekkonkinkreet.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\iPad_Only\\arthur's owl house bg ink dupe.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\iPad_Only\\Devin_Elle_Kurtz_Plant_Brushes (1).abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Legacy\\Converted Legacy Tool Presets.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Legacy\\Legacy Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Paint_Media\\Digital_Oils_JonNeimeister.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Paint_Media\\gouache.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Paint_Media\\impressionist.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Paint_Media\\oil brush.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Paint_Media\\Painter Brush.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Paint_Media\\Painting Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Paint_Media\\watercolor.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Specialty_Effects\\Blur Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Specialty_Effects\\dblightingset1.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Specialty_Effects\\Extreme Brushes Unipredator.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Specialty_Effects\\Soft_Brushes_8_By_Enav_S.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\1 Weird Texture Brush (viagpaint) .abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\12 Sponge Brushes BlackAngelBrushes_TC.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\30 Texture Brushes (ground cracks).abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\50 pretty good bg brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\Custom BG Set.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\D_Grungeset1.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\GrungeBrushes8 by KeReN-R.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\nightsky.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\pureanodyne_borders.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\RIPEgrunge_v3__photoshopbrushpack.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\s_Abstract22.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\spatter_brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\Texture Brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\tree brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Photoshop_ABR_Brushes\\Texture_Grunge\\wood texture brushes.abr");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\AnimCouleur2-Presets-cc17\\AnimCouleur2_Tools.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Kyle Webster Brushes\\Kyle_Erasers.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Kyle Webster Brushes\\KyleMrNatural.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Kyle Webster Brushes\\KyleRealWatercolor.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Kyle Webster Brushes\\KyleTilterrificBonus.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Kyle Webster Brushes\\KyleWetWildWCbrush.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Kyle Webster Brushes\\KyleXeroxBrushes.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Kyle Webster Brushes\\Megapack_Erasers.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Kyle Webster Brushes\\Megapack_FX.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Kyle Webster Brushes\\Megapack_Gen1.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Kyle Webster Brushes\\Megapack_Inkbox.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Kyle Webster Brushes\\Megapack_Mixer.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Kyle Webster Brushes\\Megapack_Paintbox.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\3 FX Brushes.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\BRNK Ink 60s Leaky.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\CtrlPaint+Basic+3+Plus.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\February 22 brushes.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\Frenden_Pencils___Inks_v1_2b.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\Frenden_Real_Pencils_v1_4.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\gabriel_custom_brushes.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\Megapack_Aliased_Pencils.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\Megapack_Drawing.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\Megapack_Special_Pencils.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\Megapack_Toothy_Techpens.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\Nem's tool presets.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\Pastel Oil .tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\Pastel Palooza.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\Sam's Tool Presets.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\Sparth - Tool Presets.tpl");
files.push("C:\\.config_Copy\\Configurations\\Photoshop\\Brushes\\Tool_Presets\\Tools\\whittoolz11042008.tpl");
var loaded = 0;
var failures = [];
for (var i = 0; i < files.length; i++) {
    try {
        app.load(new File(files[i]));
        loaded++;
    } catch (e) {
        failures.push(files[i] + " :: " + e);
    }
}
var msg = "Loaded " + loaded + " Photoshop preset files.";
if (failures.length > 0) { msg += "\nFailed: " + failures.length + "\n\n" + failures.join("\n"); }
alert(msg);
