;;; podcaster-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from podcaster.el

(autoload 'podcaster "podcaster" "\
Play podcasts." t)
(autoload 'podcaster-stop "podcaster" "\
Stop the currently-playing podcast." t)
(autoload 'podcaster-pause "podcaster" nil t)
(autoload 'podcaster-resume "podcaster" "\
Resume the currently-playing podcast." t)
(register-definition-prefixes "podcaster" '("podcaster-"))

;;; End of scraped data

(provide 'podcaster-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; podcaster-autoloads.el ends here
