;;; prosjekt-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from async-shell-command-prosjekt.el

(register-definition-prefixes "async-shell-command-prosjekt" '("prosjekt-"))


;;; Generated autoloads from find-project-file-prosjekt.el

(autoload 'prosjekt-find-project-file "find-project-file-prosjekt" "\
Find a file in the current project." t)


;;; Generated autoloads from prosjekt.el

(autoload 'prosjekt-new "prosjekt" "\
Create a new project.

(fn DIRECTORY NAME)" t)
(autoload 'prosjekt-delete "prosjekt" "\
Delete an existing project.

(fn FILENAME)" t)
(autoload 'prosjekt-open-recent "prosjekt" "\
Open a project named PROJ in the recent-list.

(fn FILENAME)" t)
(autoload 'prosjekt-open "prosjekt" "\
Open the project defined in FILENAME.

(fn FILENAME)" t)
(autoload 'prosjekt-clone "prosjekt" "\
Clone a new project from an existing project.

(fn DIRECTORY NAME CLONE_FROM)" t)
(autoload 'prosjekt-save "prosjekt" "\
Save the current project." t)
(autoload 'prosjekt-close "prosjekt" "\
Close the current project." t)
(autoload 'prosjekt-setup "prosjekt" "\
Edit the project configuration in a new buffer." t)
(autoload 'prosjekt-repopulate "prosjekt" "\
Repopulate the project." t)
(autoload 'prosjekt-run-tool-by-name "prosjekt" "\


(fn NAME)" t)
(autoload 'prosjekt-setup-save-and-close "prosjekt" "\
Save the prosjekt-buffer contents and the new project definition,
and kill that buffer." t)
(register-definition-prefixes "prosjekt" '("defun-autosave" "prosjekt-"))

;;; End of scraped data

(provide 'prosjekt-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; prosjekt-autoloads.el ends here
