;;; grizzl-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from grizzl.el

(autoload 'grizzl-make-index "grizzl" "\
Makes an index from the list STRINGS for use with `grizzl-search'.

If :PROGRESS-FN is given as a keyword argument, it is called repeatedly
with integers N and TOTAL.

If :CASE-SENSITIVE is specified as a non-nil keyword argument, the index
will be created case-sensitive, otherwise it will be case-insensitive.

(fn STRINGS &rest OPTIONS)")
(autoload 'grizzl-search "grizzl" "\
Fuzzy searches for TERM in INDEX prepared with `grizzl-make-index'.

OLD-RESULT may be specified as an existing search result to increment from.
The result can be read with `grizzl-result-strings'.

(fn TERM INDEX &optional OLD-RESULT)")
(autoload 'grizzl-result-count "grizzl" "\
Returns the number of matches present in RESULT.

(fn RESULT)")
(autoload 'grizzl-result-strings "grizzl" "\
Returns the ordered list of matched strings in RESULT, using INDEX.

If the :START option is specified, results are read from the given offset.
If the :END option is specified, up to :END results are returned.

(fn RESULT INDEX &rest OPTIONS)")
(autoload 'grizzl-completing-read "grizzl" "\
Performs a completing-read in the minibuffer using INDEX to fuzzy search.
Each key pressed in the minibuffer filters down the list of matches.

(fn PROMPT INDEX)")
(autoload 'grizzl-selected-result "grizzl" "\
Get the selected string from INDEX in a `grizzl-completing-read'.

(fn INDEX)")
(autoload 'grizzl-set-selection+1 "grizzl" "\
Move the selection up one row in `grizzl-completing-read'." t)
(autoload 'grizzl-set-selection-1 "grizzl" "\
Move the selection down one row in `grizzl-completing-read'." t)
(register-definition-prefixes "grizzl" '("*grizzl-" "grizzl-"))

;;; End of scraped data

(provide 'grizzl-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; grizzl-autoloads.el ends here
