;;; ffmpeg-player-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ffmpeg-player.el

(autoload 'ffmpeg-player-clean "ffmpeg-player" "\
Clean all the data, like images cache." t)
(autoload 'ffmpeg-player-video "ffmpeg-player" "\
Play the video with PATH.

(fn PATH)")
(register-definition-prefixes "ffmpeg-player" '("ffmpeg-player-"))

;;; End of scraped data

(provide 'ffmpeg-player-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ffmpeg-player-autoloads.el ends here
