;;; eacl-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eacl.el

(autoload 'eacl-get-project-root "eacl" "\
Get project root.")
(autoload 'eacl-current-line-info "eacl" "\
Current line.")
(autoload 'eacl-get-keyword "eacl" "\
Get trimmed keyword from LINE.
If SPACE-P is t, space characters are converted to pattern matching any string.

(fn LINE &optional SPACE-P)")
(autoload 'eacl-complete-line "eacl" "\
Complete line by grepping in root.
The selected region replaces current line first.
The text from line beginning to current point is used as grep keyword.
Whitespace in the keyword matches any characters.
If DELETED-P is t and Git is used, complete from deleted code.

(fn &optional DELETED-P)" t)
(autoload 'eacl-complete-multiline "eacl" "\
Complete multi-line code or html tag.
The selected region will replace current line first.
The text from line beginning to current point is used as grep keyword.
Whitespace in keyword could match any characters." t)
(register-definition-prefixes "eacl" '("eacl-"))

;;; End of scraped data

(provide 'eacl-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eacl-autoloads.el ends here
