;;; wgrep-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from wgrep.el

(autoload 'wgrep-setup "wgrep" "\
Setup wgrep preparation.")
(add-hook 'grep-setup-hook 'wgrep-setup)
(register-definition-prefixes "wgrep" '("wgrep-"))


;;; Generated autoloads from wgrep-ack.el

(autoload 'wgrep-ack-and-a-half-setup "wgrep-ack")
(autoload 'wgrep-ack-setup "wgrep-ack")
(add-hook 'ack-and-a-half-mode-hook 'wgrep-ack-and-a-half-setup)
(add-hook 'ack-mode-hook 'wgrep-ack-setup)
(register-definition-prefixes "wgrep-ack" '("wgrep-ack-"))


;;; Generated autoloads from wgrep-ag.el

(autoload 'wgrep-ag-setup "wgrep-ag")
(add-hook 'ag-mode-hook 'wgrep-ag-setup)
(register-definition-prefixes "wgrep-ag" '("wgrep-ag-"))


;;; Generated autoloads from wgrep-helm.el

(autoload 'wgrep-helm-setup "wgrep-helm")
(add-hook 'helm-grep-mode-hook 'wgrep-helm-setup)
(add-hook 'helm-occur-mode-hook 'wgrep-helm-setup)
(register-definition-prefixes "wgrep-helm" '("wgrep-helm-"))


;;; Generated autoloads from wgrep-pt.el

(autoload 'wgrep-pt-setup "wgrep-pt")
(add-hook 'pt-search-mode-hook 'wgrep-pt-setup)
(register-definition-prefixes "wgrep-pt" '("wgrep-pt-unload-function"))


;;; Generated autoloads from wgrep-subtest.el

(register-definition-prefixes "wgrep-subtest" '("wgrep-test--ag"))


;;; Generated autoloads from wgrep-test.el

(register-definition-prefixes "wgrep-test" '("wgrep-test"))

;;; End of scraped data

(provide 'wgrep-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; wgrep-autoloads.el ends here
