;;; stimmung-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from stimmung-themes.el

(autoload 'stimmung-themes-load-dark "stimmung-themes" "\
Load `stimmung-dark' and disable `stimmung-light'." t)
(autoload 'stimmung-themes-load-light "stimmung-themes" "\
Load `stimmung-light' and disable `stimmung-dark'." t)
(autoload 'stimmung-themes--toggle-prompt "stimmung-themes" "\
Helper for `stimmung-themes-toggle'.")
(autoload 'stimmung-themes-toggle "stimmung-themes" "\
Toggle between the dark and light version of `stimmung-themes'.
Prompt the user for which to pick in case none is enabled.
Currently assumes the themes is loaded, which might be an issue.
Inspired by stimmung-themes." t)
(register-definition-prefixes "stimmung-themes" '("stimmung-themes-"))


;;; Generated autoloads from stimmung-themes-dark-theme.el

(when (and (boundp 'custom-theme-load-path) load-file-name) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "stimmung-themes-dark-theme" '("stimmung-themes-dark"))


;;; Generated autoloads from stimmung-themes-light-theme.el

(when (and (boundp 'custom-theme-load-path) load-file-name) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "stimmung-themes-light-theme" '("stimmung-themes-light"))

;;; End of scraped data

(provide 'stimmung-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; stimmung-themes-autoloads.el ends here
