---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: ok
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/ok/.config/syncthing/config-4:/config
      - /run/media/ok/easystore/Music:/data/music
      - /home/ok/.config/syncthing/2026:/2026	
      - /home/ok/Music:/music
      - /home/ok/ok:/ok
      - /home/ok/ref:/ref
      - /home/ok/ref-v:/ref-v
      - /home/ok/Videos/Screen-Recordings/:/Screen-Recordings
      - /home/ok/Videos/videosnow:/videosnow
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
