;;; curl-to-elisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from curl-to-elisp.el

(autoload 'curl-to-elisp-httpie-to-elisp "curl-to-elisp" "\
Convert httpie/curlie COMMAND to Emacs Lisp expression.

Return the expression.

When called interactively or PRINT is non-nil, also pretty-print
the expression in echo area.

(fn COMMAND &optional PRINT)" t)
(autoload 'curl-to-elisp "curl-to-elisp" "\
Convert cURL COMMAND to Emacs Lisp expression, return the expression.

When called interactively or PRINT is non-nil, also pretty-print
the expression in echo area.

(fn COMMAND &optional PRINT)" t)
(autoload 'curl-to-elisp-verb "curl-to-elisp" "\
Convert cURL COMMAND to verb request specification, return the specification.

When INSERT is non-nil, insert the result at point.

For verb request specification, see URL
`https://github.com/federicotdn/verb#writing-request-specifications'.

(fn COMMAND &optional INSERT)" t)
(register-definition-prefixes "curl-to-elisp" '("curl-to-elisp-"))

;;; End of scraped data

(provide 'curl-to-elisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; curl-to-elisp-autoloads.el ends here
