;;; echo-bar-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from echo-bar.el

(defvar echo-bar-mode nil "\
Non-nil if Echo-Bar mode is enabled.
See the `echo-bar-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `echo-bar-mode'.")
(custom-autoload 'echo-bar-mode "echo-bar" nil)
(autoload 'echo-bar-mode "echo-bar" "\
Display text at the end of the echo area.

This is a global minor mode.  If called interactively, toggle the
`Echo-Bar mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='echo-bar-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'echo-bar-enable "echo-bar" "\
Turn on the echo bar." t)
(autoload 'echo-bar-disable "echo-bar" "\
Turn off the echo bar." t)
(register-definition-prefixes "echo-bar" '("echo-bar-"))

;;; End of scraped data

(provide 'echo-bar-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; echo-bar-autoloads.el ends here
