;;; distel-completion-lib-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from distel-completion-lib.el

(register-definition-prefixes "distel-completion-lib" '("&distel-completion-receive-" "distel-completion-"))

;;; End of scraped data

(provide 'distel-completion-lib-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; distel-completion-lib-autoloads.el ends here
