---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: pc
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - C:/Users/ok/docker/syncthing/config:/config
      - C:/2026:/2026
    ports:
      - 127.0.0.1:8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped