;;; auto-complete-sage-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from auto-complete-sage.el

(autoload 'ac-sage-setup "auto-complete-sage" nil t)
(register-definition-prefixes "auto-complete-sage" '("ac-s" "as-source-sage-repl-argspec"))

;;; End of scraped data

(provide 'auto-complete-sage-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; auto-complete-sage-autoloads.el ends here
