#+title: After Effects: Notes
* What is After Effects? 
- After Effects is for compositing
- compositing is when you take all of your animation and drawings - layers and put it all together.
- Like a multi-plane animation would be done in After Effects
which include your
- OL - Overlays - (foreground elements)
- CH - Character Animation 
- BG - Background
- UL - Underlays


** Composition

* Parallax Background
** Canvas Size
create the canvas size which is the size of your canvas.

** Resize

** Parent

** Add Keyframe button

** Everything moves
- because they are all parented they will all move together

** Seperate them 
- seperate the layers so they don't move together and vary in spacing

** Ease-in and Ease-Out
- select the keyframes 
- go to Keyframe Assistant
- click Easy Ease In


* More Notes
** Pre-Compose 
- for loops and animating you have to pre compose
** Keys -
start at the beginning of what you want to move -
when you move, scale, or change an 'element' in ae you create a key at the beginning which clicks on the stopwatch
and it also creates a little dot on your timeline
those are your keys they control when that action happens
from there you can change the speed how smooth that is by changing the graphs of the movement
** Graph Editor -
make sure graph is selected 
click the graph view and it will show the graph of whatever you have graphed and selected
** Loop - (written <2025-08-21 Thu 11:10>)
to loop animation alt - click on the stopwatch (I think) or hold down u and click the timer button which will allow you to put in expressions
type in loopOut(); or loopOut(“cycle”); and it will cycle through your keys for the duration of the scene
make sure to drag it out all the way 
[[https://www.schoolofmotion.com/blog/loop-expression-after-effects][link]]
** Render Queue
- Render Queue is where you send your scene to export it and then you click render and it renders. 
once you do that you can 
** Purge 
Edit > Purge - delete cache 
- periodically click purge cache and you can then delete the cache which will clean up space on your hard drive for After Effects to keep running.
** Region of Interest 
to select and area click region of interest - you can then comp the project to the are
