#+title: Command Line
* Hide
hide things in windows using 
attrib +h file 
in the terminal
shutdown -s -t timeInSeconds
* Grep
- Use Grep to find files
** Find
*** To find a phrase in a folder search like this
grep -r "'4c566a" ~/.config/fish/
#!/bin/bash
*** or
based on grep -E '/mnt/.+\.(jpg|jpeg|png|pdf|eps)' notes.org | ./gen_tex.sh | clip.exe
** cat file  
*** to copy to the clipboard
cat file.org | to_latex.sh | xclip -selection clipboard
*** to write text to a file
echo "text" >> filename.org
** to write text into file from terminal
echo "Your text here" > filename.org
** 
cat >> filename.org
echo "text"
** 
cat >> my_notes.org
echo "This is another line in the file."
cat
* Start programs from cmd
cmd.exe /c "file exe"
* Git 
** Git 
update 
git push
** oh my posh
oh-my-posh init pwsh --config "$env:C:\Posh\THemes\bubbles.omp.json"
(@(& 'C:/Users/zacha/scoop/apps/oh-my-posh/current/oh-my-posh.exe' init pwsh --config='C:\Posh\THemes\bubbles.omp.json' --print) -join "`n") | Invoke-Expression
** Moving around
- tab to move down
  - shift tab to move up
    alt tab - to move along windows
    alt shift tab -  to move along windows in the opposite direction
        - ctrl + k works a lot for searching
  - ctrl + l usually works for searching as well
        - ctrl + g works a lot for entering
        - ctrl + j
        - ctrl + k also usually work a lot for entering along with the enter button itself
* Terminal 
** MPV
** ffmpeg
use this in terminal to export avi files to mp4 
[[ ffmpeg -i filepath.avi filename.mp4]] ** to export to convert to mp4 file
 ffmpeg -i input.avi -r 24 output.mp4
-fs limit_size (output)
Set the file size limit, expressed in bytes. No further chunk of bytes is written after the limit is exceeded. The size of the output file is slightly more than the requested file size
** syncthing
** ncdu
** btop
** fzf
fzf is for fuzzy finding in the terminal. Search inside the directory by typing fzf in the directory that you are in.
** zoxide
makes searching easy by typing in z it just goes right to the place
** Pastel
for looking up colors
* oh-my-posh
** oh-my-posh in bash
 for using oh-my-posh in bash
eval "$(oh-my-posh init bash --config ~/jandedobbeleer.omp.json)"
add this in to either ~/.bashrc or ~/.profile or ~/.bash_profile
then reload using exec bash 
or
eval "$(oh-my-posh init bash)"
