dos2unix /home/ok/.dotfiles/sh/convert/cnv_heic_j.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_heic_jpeg2026.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_heic_to_jpeg.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_jpg_pdf.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_m4a_mp3.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_mp4_frames.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_mp4_gif.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_op_mp3.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_org_docx.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_pdf__jpg.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_pdf_jpg.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_pj.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_png_j.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_psd_j.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_webloc_jpeg.sh
dos2unix /home/ok/.dotfiles/sh/convert/cnv_webp_jpeg.sh
dos2unix /home/ok/.dotfiles/sh/convert/jfif_jpeg.sh
dos2unix /home/ok/.dotfiles/sh/convert/latex_export.sh
dos2unix /home/ok/.dotfiles/sh/convert/untar.sh
dos2unix /home/ok/.dotfiles/sh/delete/clean.sh
dos2unix /home/ok/.dotfiles/sh/delete/del_csp.sh
dos2unix /home/ok/.dotfiles/sh/delete/deldoop.sh
dos2unix /home/ok/.dotfiles/sh/delete/delete_all_heic.sh
dos2unix /home/ok/.dotfiles/sh/delete/delete_all_jfif.sh
dos2unix /home/ok/.dotfiles/sh/delete/delete_duplicate_images.sh
dos2unix /home/ok/.dotfiles/sh/delete/delete_duplicates.sh
dos2unix /home/ok/.dotfiles/sh/delete/delete_text_string.sh
dos2unix /home/ok/.dotfiles/sh/delete/X.fish
dos2unix /home/ok/.dotfiles/sh/delete/X.sh
dos2unix /home/ok/.dotfiles/sh/export/copy_out.sh
dos2unix /home/ok/.dotfiles/sh/export/download-.sh
dos2unix /home/ok/.dotfiles/sh/export/export_org_to_pdf.sh
dos2unix /home/ok/.dotfiles/sh/export/export_org_to_pdf_02.sh
dos2unix /home/ok/.dotfiles/sh/export/export_org_to_pdf_02.sh~
dos2unix /home/ok/.dotfiles/sh/export/F2_txt.sh
dos2unix /home/ok/.dotfiles/sh/export/sequence_.sh
dos2unix /home/ok/.dotfiles/sh/export/tex.sh
dos2unix /home/ok/.dotfiles/sh/file/copy_clip2.sh
dos2unix /home/ok/.dotfiles/sh/file/FI_^^.sh
dos2unix /home/ok/.dotfiles/sh/file/filecopyimg.sh
dos2unix /home/ok/.dotfiles/sh/file/filecopyimgmultiple.sh
dos2unix /home/ok/.dotfiles/sh/file/filecopyimgmultiple02.sh
dos2unix /home/ok/.dotfiles/sh/file/filecopyimgmultiple03.sh
dos2unix /home/ok/.dotfiles/sh/file/filecopyimgmultiple_1.sh
dos2unix /home/ok/.dotfiles/sh/file/filepath.sh
dos2unix /home/ok/.dotfiles/sh/file/filepathcopy.sh
dos2unix /home/ok/.dotfiles/sh/fix/arch-audio
dos2unix /home/ok/.dotfiles/sh/fix/fix.sh
dos2unix /home/ok/.dotfiles/sh/fix/list.sh
dos2unix /home/ok/.dotfiles/sh/fix/listlist.sh
dos2unix /home/ok/.dotfiles/sh/format/bracket_format.sh
dos2unix /home/ok/.dotfiles/sh/format/bracket_format.sh~
dos2unix /home/ok/.dotfiles/sh/format/grep_t.sh
dos2unix /home/ok/.dotfiles/sh/format/grep_thumbnails.sh~
dos2unix /home/ok/.dotfiles/sh/format/to_latex.sh
dos2unix /home/ok/.dotfiles/sh/install/install-syncthing.sh
dos2unix /home/ok/.dotfiles/sh/install/ok-install-beets.sh
dos2unix /home/ok/.dotfiles/sh/install/ok-install-f.sh
dos2unix /home/ok/.dotfiles/sh/install/ok-install-fi.sh
dos2unix /home/ok/.dotfiles/sh/install/ok-install-go.sh
dos2unix /home/ok/.dotfiles/sh/install/ok-install-nano-calender.sh
dos2unix /home/ok/.dotfiles/sh/install/ok-install-oh-my-posh.sh
dos2unix /home/ok/.dotfiles/sh/install/ok-install-py.sh
dos2unix /home/ok/.dotfiles/sh/install/ok-install-scoop.sh
dos2unix /home/ok/.dotfiles/sh/install/ok-install-syncthing.sh
dos2unix /home/ok/.dotfiles/sh/install/ok-install-zotero.sh
dos2unix /home/ok/.dotfiles/sh/launch/ghostty-launcher.sh
dos2unix /home/ok/.dotfiles/sh/launch/open_tvpaint.sh
dos2unix /home/ok/.dotfiles/sh/launch/syncthing_start.sh
dos2unix /home/ok/.dotfiles/sh/launch/syncthing_stop-02.sh
dos2unix /home/ok/.dotfiles/sh/launch/syncthing_stop.sh
dos2unix /home/ok/.dotfiles/sh/make/autocaption.sh
dos2unix /home/ok/.dotfiles/sh/make/autocaption_1.sh
dos2unix /home/ok/.dotfiles/sh/make/merge_mp3.bash
dos2unix /home/ok/.dotfiles/sh/make/merge_pdf.sh
dos2unix /home/ok/.dotfiles/sh/make/mkdup.sh
dos2unix /home/ok/.dotfiles/sh/make/mkpdf.sh
dos2unix /home/ok/.dotfiles/sh/make/mkto.sh
dos2unix /home/ok/.dotfiles/sh/make/save_screen.sh
dos2unix /home/ok/.dotfiles/sh/make/save_screen_v2.sh
dos2unix /home/ok/.dotfiles/sh/make/screen_record
dos2unix /home/ok/.dotfiles/sh/make/yt-dl.sh
dos2unix /home/ok/.dotfiles/sh/maketiny/compress_video.sh
dos2unix /home/ok/.dotfiles/sh/maketiny/maketiny-img.fish
dos2unix /home/ok/.dotfiles/sh/maketiny/maketiny-png.fish
dos2unix /home/ok/.dotfiles/sh/maketiny/tiny_vid_split.sh
dos2unix /home/ok/.dotfiles/sh/move/FI_^.sh
dos2unix /home/ok/.dotfiles/sh/plan/0T5.sh
dos2unix /home/ok/.dotfiles/sh/ps1/cnvheic2j.ps1
dos2unix /home/ok/.dotfiles/sh/ps1/config-install.ps1
dos2unix /home/ok/.dotfiles/sh/ps1/rename.ps1
dos2unix /home/ok/.dotfiles/sh/psd/16x9.sh
dos2unix /home/ok/.dotfiles/sh/psd/crop.sh
dos2unix /home/ok/.dotfiles/sh/psd/psd_bright.py
dos2unix /home/ok/.dotfiles/sh/psd/psd_bright_pencil.py
dos2unix /home/ok/.dotfiles/sh/psd/psd_bw.py
dos2unix /home/ok/.dotfiles/sh/psd/psd_fill.py
dos2unix /home/ok/.dotfiles/sh/psd/psd_fill.sh
dos2unix /home/ok/.dotfiles/sh/psd/psd_fill_extra.sh
dos2unix /home/ok/.dotfiles/sh/psd/psd_fill_working.py
dos2unix /home/ok/.dotfiles/sh/psd/psd_flat.sh
dos2unix /home/ok/.dotfiles/sh/psd/psd_flats.sh
dos2unix /home/ok/.dotfiles/sh/psd/psd_jpeg.sh
dos2unix /home/ok/.dotfiles/sh/psd/psd_key_matte_folder.sh
dos2unix /home/ok/.dotfiles/sh/psd/psd_key_matte_folder_strong.sh
dos2unix /home/ok/.dotfiles/sh/psd/psd_keyout.sh
dos2unix /home/ok/.dotfiles/sh/psd/psd_keyout_soft.sh
dos2unix /home/ok/.dotfiles/sh/psd/psd_keyout_w_matte.sh
dos2unix /home/ok/.dotfiles/sh/psd/psd_keyout_w_matte_soft.sh
dos2unix /home/ok/.dotfiles/sh/psd/psd_select_sub.sh
dos2unix /home/ok/.dotfiles/sh/rename/f2.sh
dos2unix /home/ok/.dotfiles/sh/rename/F2_date_taken.sh
dos2unix /home/ok/.dotfiles/sh/rename/iph.sh
dos2unix /home/ok/.dotfiles/sh/rename/rename.sh
dos2unix /home/ok/.dotfiles/sh/rename/rename_blank.sh
dos2unix /home/ok/.dotfiles/sh/rename/rename_date_taken.sh
dos2unix /home/ok/.dotfiles/sh/rename/rename_folder.sh
dos2unix /home/ok/.dotfiles/sh/rename/rename_still_life.sh
dos2unix /home/ok/.dotfiles/sh/rename/rm_not_cropped.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/F2.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/F2_date_taken.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/F2_date_taken_1.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/F2_date_taken_1.sh~
dos2unix /home/ok/.dotfiles/sh/shell_files/F2_folder.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/F2_folder.sh~
dos2unix /home/ok/.dotfiles/sh/shell_files/F2iph.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/F2iph.sh~
dos2unix /home/ok/.dotfiles/sh/shell_files/filecopyimg.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/filecopyimgmultiple.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/filecopyimgmultiple02.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/filecopyimgmultiple03.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/filepath.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/filepathcopy.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/forward_slashes-to-backward_slashes.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/ghostty-launcher.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/heic__jpg.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/heic_jpeg.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/jfif_jpeg.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/jpeg.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/move_files_to_parent.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/png-j.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/png-recursive.ps1
dos2unix /home/ok/.dotfiles/sh/shell_files/psd2jpeg.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/psd_convert.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/psd_jpeg_w_gimp.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/syncthing.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/tiny_vid.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/UTO.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/webloc_jpeg.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/webloc_jpeg_02.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/webloc_jpeg_1.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/webp_jpeg.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/X.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/X_all_heic.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/X_all_jfif.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/X_duplicate_images.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/X_duplicates.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/X_text_string.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/Xdoop.sh
dos2unix /home/ok/.dotfiles/sh/shell_files/Xdoop.sh~
dos2unix /home/ok/.dotfiles/sh/shell_files/Xdoop_1.sh
