(setq inhibit-startup-echo-area-message "tychoish")
(setq inhibit-startup-message t)
(setq initial-major-mode 'fundamental-mode)
(setq initial-scratch-message 'nil)
(setq initial-buffer-choice nil) 
(setq org-image-actual-width (list 500))
(cua-mode t)
(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(setq org-agenda-files '("~/.ok/ok"))
(setq cfw:org-agenda-schedule-args '(:SCHEDULED))
(setq cfw:org-agenda-schedule-args '(:scheduled))
(setq cfw:org-overwrite-default-keybinding t)
(setq org-duration-format 'h:mm)
(setq frame-title-format '((:eval default-directory)))
(desktop-save-mode 0)
(global-set-key (kbd "C-c e") 'beginning-of-line)
(global-set-key (kbd "C-c 2") #'fzf)
(global-set-key (kbd "C-c a") #'org-agenda)
(global-set-key (kbd "C-c q") 'make-directory)
(global-set-key (kbd "C-c t") 'set-frame-alpha)
(global-set-key (kbd "C-c l") #'org-store-link)    
(global-set-key (kbd "C-c a") #'org-agenda) 
(global-set-key (kbd "C-c c") #'org-capture)  
(global-set-key (kbd "C-c f") #'neotree-dir)
(global-set-key (kbd "C-c h") #'neotree-toggle)
(global-set-key (kbd "C-c g") #'0blayout-switch)
(global-set-key (kbd "C-c w") 'peep-dired)
(global-set-key (kbd "C-c h") 'httpd-serve-directory)
(global-set-key (kbd "C-c e") 'impatient-mode)
(global-set-key (kbd "C-c m") 'magit)
(global-set-key (kbd "C-c r") 'counsel-outline)
(global-set-key (kbd "C-c i") 'overwrite-mode)
(global-set-key (kbd "C-c d") 'org-clock-timestamps-down) 
(global-set-key (kbd "C-c e") 'org-clock-timestamps-up) 
(global-set-key (kbd "C-c e") 'org-clock-timestamps-up) 
(global-set-key (kbd "C-c q") 'make-directory)
(global-set-key (kbd "C-c t") 'set-frame-alpha)
(global-set-key (kbd "C-c l") #'org-store-link)    
(global-set-key (kbd "C-c a") #'org-agenda) 
(global-set-key (kbd "C-c c") #'org-capture)  
(global-set-key (kbd "C-c f") #'neotree-dir)
(global-set-key (kbd "C-c h") #'neotree-toggle)
(global-set-key (kbd "C-c g") #'0blayout-switch)
(global-set-key (kbd "C-c w") 'peep-dired)
(global-set-key (kbd "C-c h") 'httpd-serve-directory)
(global-set-key (kbd "C-c e") 'impatient-mode)
(global-set-key (kbd "C-c m") 'magit)
(global-set-key (kbd "C-c r") 'counsel-outline)
(global-set-key (kbd "C-c i") 'overwrite-mode)
(global-set-key (kbd "C-c d") 'org-clock-timestamps-down) 
(global-set-key (kbd "C-c e") 'org-clock-timestamps-up) 
(global-set-key (kbd "C-c e") 'org-clock-timestamps-up)
(tool-bar-mode -1)               
(menu-bar-mode -1)               
(scroll-bar-mode -1)             
(cua-mode t) 

(setq visible-bell 1)
;; (set-frame-parameter (selected-frame) 'alpha '(95 . 95)) 
;; this doesn't work in the terminal
(setq frame-title-format '((:eval default-directory)))
(setq use-package-always-ensure t)
(require 'org)
(setq org-latex-listings 'minted)
(setq org-startup-with-inline-images t)
(setq org-image-actual-width (list 260))
(setq TeX-view-program-selection '((output-pdf "PDF Tools"))
      TeX-view-program-list '(("PDF Tools" TeX-pdf-tools-sync-view))
      TeX-source-correlate-start-server t)
(setq pdf-view-use-scaling t)
(setq pdf-view-resize-factor 1.05)
(setq org-duration-format 'h:mm)
(global-set-key (kbd "C-c q") 'make-directory)
(global-set-key (kbd "C-c t") 'set-frame-alpha)
(global-set-key (kbd "C-c n f") 'org-roam-node-find)
(global-set-key (kbd "C-c l") #'org-store-link)    
(global-set-key (kbd "C-c a") #'org-agenda)
(global-set-key (kbd "C-c c") #'org-capture)  
(global-set-key (kbd "C-c f") #'neotree-dir)
(global-set-key (kbd "C-c h") #'neotree-toggle)
(global-set-key (kbd "C-c g") #'0blayout-switch)
(global-set-key (kbd "C-c w") 'peep-dired)
(global-set-key (kbd "C-c h") 'httpd-serve-directory)
(global-set-key (kbd "C-c e") 'impatient-mode)
(global-set-key (kbd "C-c m") 'magit)
(global-set-key (kbd "C-c r") 'counsel-outline)
(global-set-key (kbd "C-c i") 'overwrite-mode)
(global-set-key (kbd "C-c d") 'org-clock-timestamps-down) 
(global-set-key (kbd "C-c e") 'org-clock-timestamps-up)
  :ensure t
  :config

(setq enable-local-eval t)
(setq safe-local-eval-forms '((progn (org-agenda-list) (other-window 1))))
(add-to-list 'load-path "~/.emacs.d/compat")
(add-to-list 'load-path "~/.emacs.d/dash")
(add-to-list 'load-path "~/.emacs.d/transient/")
(add-to-list 'load-path "~/.emacs.d/with-editor")



(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(emacsql sql-indent zoxide web-mode peep-dired openwith neotree magit kaolin-themes ivy impatient-mode google-translate fzf doom-themes dired-sidebar company catppuccin-theme calfw-org calfw-ical calfw base16-theme)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(load-theme 'base16-hopscotch t)
(ivy-mode t)
(require 'calfw)

(require 'calfw-org)

