;;; weechat-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from weechat.el

(autoload 'weechat-connect "weechat" "\
Connect to WeeChat.

HOST is the relay host, `weechat-host-default' by default.
PORT is the port where the relay listens, `weechat-port-default' by default.
PASSWORD is either a string, a function or nil.
MODE is null or 'plain for a plain socket, t or 'ssl for a TLS socket;
a string denotes a command to run.  You can use %h and %p to interpolate host
and port number respectively.

(fn &optional HOST PORT PASSWORD MODE FORCE-DISCONNECT)" t)
(register-definition-prefixes "weechat" '("weechat-"))


;;; Generated autoloads from weechat-button.el

(register-definition-prefixes "weechat-button" '("weechat-button-"))


;;; Generated autoloads from weechat-cmd.el

(register-definition-prefixes "weechat-cmd" '("weechat-cmd-"))


;;; Generated autoloads from weechat-color.el

(register-definition-prefixes "weechat-color" '("weechat-"))


;;; Generated autoloads from weechat-complete.el

(register-definition-prefixes "weechat-complete" '("pcomplete" "weechat-"))


;;; Generated autoloads from weechat-core.el

(register-definition-prefixes "weechat-core" '("weechat-"))


;;; Generated autoloads from weechat-corrector.el

(register-definition-prefixes "weechat-corrector" '("weechat-corrector-"))


;;; Generated autoloads from weechat-image.el

(register-definition-prefixes "weechat-image" '("weechat-image-"))


;;; Generated autoloads from weechat-latex.el

(register-definition-prefixes "weechat-latex" '("weechat-latex-"))


;;; Generated autoloads from weechat-notifications.el

(register-definition-prefixes "weechat-notifications" '("weechat-"))


;;; Generated autoloads from weechat-read-marker.el

(register-definition-prefixes "weechat-read-marker" '("weechat-read-marker-"))


;;; Generated autoloads from weechat-relay.el

(register-definition-prefixes "weechat-relay" '("weechat-"))


;;; Generated autoloads from weechat-secrets.el

(register-definition-prefixes "weechat-secrets" '("weechat-secrets-"))


;;; Generated autoloads from weechat-smiley.el

(register-definition-prefixes "weechat-smiley" '("weechat-smiley-"))


;;; Generated autoloads from weechat-speedbar.el

(register-definition-prefixes "weechat-speedbar" '("weechat-speedbar-"))


;;; Generated autoloads from weechat-spelling.el

(register-definition-prefixes "weechat-spelling" '("weechat-"))


;;; Generated autoloads from weechat-tracking.el

(register-definition-prefixes "weechat-tracking" '("weechat-tracking-"))

;;; End of scraped data

(provide 'weechat-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; weechat-autoloads.el ends here
