#!/bin/bash
unlink /usr/local/bin/cnv_pdf__jpg.sh
unlink /usr/local/bin/cnv_pdf_jpg.sh
unlink /usr/local/bin/convert-path
unlink /usr/local/bin/convert_heic_to_jpeg.sh
unlink /usr/local/bin/convert_heic_to_jpg.sh
unlink /usr/local/bin/convert_png_j.sh
unlink /usr/local/bin/convert_webloc_to_jpeg.sh
unlink /usr/local/bin/convert_webp_jpeg.sh
unlink /usr/local/bin/heic_jpeg.sh
unlink /usr/local/bin/jfif_jpeg.sh
unlink /usr/local/bin/mp4_frames.sh
unlink /usr/local/bin/psd_convert.sh
unlink /usr/local/bin/clean.sh
unlink /usr/local/bin/deldoop.sh
unlink /usr/local/bin/delete_all_heic.sh
unlink /usr/local/bin/delete_all_jfif.sh
unlink /usr/local/bin/delete_duplicate_images.sh
unlink /usr/local/bin/delete_duplicates.sh
unlink /usr/local/bin/delete_text_string.sh
unlink /usr/local/bin/copy_out.sh
unlink /usr/local/bin/export_org_to_pdf.sh
unlink /usr/local/bin/export_org_to_pdf_02.sh
unlink /usr/local/bin/copy_clip2.sh
unlink /usr/local/bin/FI_^^.sh
unlink /usr/local/bin/filecopyimg.sh
unlink /usr/local/bin/filecopyimgmultiple02.sh
unlink /usr/local/bin/filecopyimgmultiple03.sh
unlink /usr/local/bin/filecopyimgmultiple_1.sh
unlink /usr/local/bin/filepath.sh
unlink /usr/local/bin/filepathcopy.sh
unlink /usr/local/bin/bracket_format.sh
unlink /usr/local/bin/grep_t.sh
unlink /usr/local/bin/grep_thumbnails.sh
unlink /usr/local/bin/to_latex.sh
unlink /usr/local/bin/autocaption.sh
unlink /usr/local/bin/autocaption_1.sh
unlink /usr/local/bin/syncthing.sh
unlink /usr/local/bin/syncthing_stop.sh
unlink /usr/local/bin/merge_mp3.bash
unlink /usr/local/bin/mkdup.sh
unlink /usr/local/bin/mkpdf.sh
unlink /usr/local/bin/mkto.sh
unlink /usr/local/bin/save_screen.sh
unlink /usr/local/bin/screen_record
unlink /usr/local/bin/0T5.sh
unlink /usr/local/bin/compress_video.sh
unlink /usr/local/bin/tiny_vid_split.sh
unlink /usr/local/bin/16x92.sh
unlink /usr/local/bin/psd_bright.py
unlink /usr/local/bin/psd_bright_pencil.py
unlink /usr/local/bin/psd_bw.py
unlink /usr/local/bin/psd_fill.py
unlink /usr/local/bin/psd_fill.sh
unlink /usr/local/bin/psd_fill_extra.sh
unlink /usr/local/bin/psd_fill_working.py
unlink /usr/local/bin/psd_flat.sh
unlink /usr/local/bin/psd_flats.sh
unlink /usr/local/bin/psd_jpeg.sh
unlink /usr/local/bin/psd_key_matte_folder.sh
unlink /usr/local/bin/psd_key_matte_folder_strong.sh
unlink /usr/local/bin/psd_keyout.sh
unlink /usr/local/bin/psd_keyout_soft.sh
unlink /usr/local/bin/psd_keyout_w_matte.sh
unlink /usr/local/bin/psd_keyout_w_matte_soft.sh
unlink /usr/local/bin/iph.sh
unlink /usr/local/bin/rename.sh
unlink /usr/local/bin/rename_date_taken.sh
unlink /usr/local/bin/rename_folder.sh
unlink /usr/local/bin/heic__jpg.sh
unlink /usr/local/bin/jpeg.sh
unlink /usr/local/bin/move_files_to_parent.sh
unlink /usr/local/bin/png-j.sh
unlink /usr/local/bin/png-recursive.ps1
unlink /usr/local/bin/psd2jpeg.sh
unlink /usr/local/bin/webloc_jpeg_02.sh
unlink /usr/local/bin/webp_jpeg.sh
unlink /usr/local/bin/X.fish
