#!/bin/bash
git restore 0T5.sh
git restore 16x9.sh
git restore 16x92.sh
git restore F2_date_taken.sh
git restore F2_txt.sh
git restore FI_^.sh
git restore FI_^^.sh
git restore X.fish~
git restore X.sh
git restore autocaption.sh:Zone.Identifier
git restore backup.txt
git restore bracket_format.sh
git restore bracket_format.sh~
git restore caption.py
git restore clean.sh
git restore cnv_jpg_pdf.sh
git restore cnv_pdf__jpg.sh
git restore cnv_pdf_jpg.sh
git restore compress_video.sh
git restore compress_video2.sh
git restore convert-path
git restore convert_heic_to_jpeg.sh
git restore convert_heic_to_jpg.sh
git restore convert_png_j.sh
git restore convert_webloc_jpeg.sh
git restore convert_webloc_to_jpeg.sh
git restore convert_webp_jpeg.sh
git restore copy_clip2.sh
git restore copy_out.sh
git restore crop.sh
git restore deldoop.sh
git restore deldoop2.sh
git restore delete_all_heic.sh
git restore delete_all_jfif.sh
git restore delete_duplicate_images.sh
git restore delete_duplicates.sh
git restore delete_text_string.sh
git restore export_org_to_pdf.sh
git restore export_org_to_pdf.sh~
git restore export_org_to_pdf_02.org
git restore export_org_to_pdf_02.sh
git restore export_org_to_pdf_02.sh~
git restore f2.sh
git restore filecopyimg.sh
git restore filecopyimgmultiple.sh
git restore filecopyimgmultiple02.sh
git restore filecopyimgmultiple03.sh
git restore filecopyimgmultiple_1.sh
git restore filepath.sh
git restore filepathcopy.sh
git restore ghostty-launcher.sh
git restore grep_t.sh
git restore grep_thumbnails.sh
git restore grep_thumbnails.sh~
git restore heic_jpeg.sh
git restore iph.sh
git restore jfif_jpeg.sh
git restore jpeg.sh
git restore list.txt
git restore merge_mp3.bash
git restore mkdup.sh
git restore mkpdf.sh
git restore mkto.sh
git restore mkto.sh~
git restore mp4_frames.sh
git restore psd_bw.py
git restore psd_convert.sh
git restore psd_fill.py~
git restore psd_fill.sh
git restore psd_fill.sh~
git restore psd_fill_extra.sh
git restore psd_fill_working.py
git restore psd_flat.sh
git restore psd_flats.sh
git restore psd_flats.sh~
git restore psd_jpeg.sh
git restore psd_jpeg_w_gimp.sh
git restore psd_key_matte_folder.sh
git restore psd_key_matte_folder.sh~
git restore psd_key_matte_folder_strong.sh
git restore psd_keyout.sh
git restore psd_keyout.sh~
git restore psd_keyout_soft.sh
git restore psd_keyout_w_matte.sh
git restore psd_keyout_w_matte.sh~
git restore psd_keyout_w_matte_soft.sh
git restore psd_keyout_w_matte_soft.sh~
git restore psd_select_sub.sh
git restore rename.sh
git restore rename_blank.sh
git restore rename_date_taken.sh
git restore rename_folder.sh
git restore rename_still_life.sh
git restore rm_not_cropped.sh
git restore save_screen.sh
git restore save_screen.sh~
git restore screen_record
git restore sequence_.sh
git restore syncthing.sh
git restore syncthing_stop.sh
git restore syncthing_stop.sh~
git restore to_latex.sh~
git restore untar.sh
git restore webloc_jpeg.sh
git restore yt-dl.sh

