;;; org-easy-img-insert-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-easy-img-insert.el

(autoload 'org-easy-img-insert "org-easy-img-insert" "\
Automatically embed web image (IMG-LINK) with a name (IMG-NAME) and an optional caption (IMG-CAPTION) at cursor position in 'org-mode'.

(fn IMG-LINK IMG-NAME IMG-CAPTION)" t)
(register-definition-prefixes "org-easy-img-insert" '("org-easy-img--"))

;;; End of scraped data

(provide 'org-easy-img-insert-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-easy-img-insert-autoloads.el ends here
