;;; fuzzy-finder-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from fuzzy-finder.el

(autoload 'fuzzy-finder "fuzzy-finder" "\
Execute fuzzy-finder application.

Open a term buffer and start fuzzy-finder process using ARGUMENTS.
After the process exits successfully call ACTION function with selected items.

All arguments are optional keyword arguments.
There is a variable that defines default value for each argument except for
DIRECTORY.  For example, `fuzzy-finder-default-arguments' for the ARGUMENTS key.

`:directory DIRECTORY'
    Set the directory to start fuzzy-finder application from.
    If not given current `default-directory' will be used.

`:arguments ARGUMENTS'
    Command line arguments to be passed to `fuzzy-finder-executable'.

`:input-command INPUT-COMMAND'
    When non-empty string is given for INPUT-COMMAND, the stdout of this
    command result will be piped (\"|\") into the the fuzzy-finder process.
    Otherwise, fuzzy-finder process will be invoked without any input, thus
    the application default might be used (\"$FZF_DEFAULT_COMMAND\" for
    example).

`:action ACTION'
    Callback function that results of fuzzy-finder selection will be passed to.

    This function shall accept one argument RESULTS.
    RESULTS is a list of string of fuzzy-finder selection: it will be made by
    splitting stdout of command by OUTPUT-DELIMITER.

`:output-delimiter OUTPUT-DELIMITER'
    Regular expression to split the command output.
    When the stdout is delimited by ASCII NUL characters, this value should be
    \"\\0\".

`:window-height WINDOW-HEIGHT'
    Interger height of window that displays fuzzy-finder buffer.

(fn &key (DIRECTORY default-directory) (ARGUMENTS fuzzy-finder-default-arguments) (INPUT-COMMAND fuzzy-finder-default-input-command) (ACTION fuzzy-finder-default-action) (OUTPUT-DELIMITER fuzzy-finder-default-output-delimiter) (WINDOW-HEIGHT fuzzy-finder-default-window-height))" t)
(autoload 'fuzzy-finder-find-files-projectile "fuzzy-finder" "\
Execute fuzzy finder and visit resulting files.

If projectile package is available and root directory is found, start from that
directory." t)
(autoload 'fuzzy-finder-goto-gitgrep-line "fuzzy-finder" "\
Select line with fuzzy finder and go to selected point in a git repository.

Run git grep command to generate input lines." t)
(register-definition-prefixes "fuzzy-finder" '("fuzzy-finder-"))

;;; End of scraped data

(provide 'fuzzy-finder-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fuzzy-finder-autoloads.el ends here
