;;; cl-libify-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cl-libify.el

(autoload 'cl-libify "cl-libify" "\
Replace cl symbol names between BEG and END with their cl-lib equivalents.

If no region is supplied, this operates on the entire
buffer.  With prefix argument PROMPT, ask the user to confirm each
replacement.

(fn BEG END)" t)
(autoload 'cl-libify-mark-cl-symbols-obsolete "cl-libify" "\
Make all the `cl' vars and functions obsolete so that byte compilation will flag their use." t)
(register-definition-prefixes "cl-libify" '("cl-libify-"))

;;; End of scraped data

(provide 'cl-libify-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cl-libify-autoloads.el ends here
